name: Schedule CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
